# Generated by Django 4.2.3 on 2023-07-27 18:29

import cronapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, null=True)),
                ('year', models.PositiveIntegerField(null=True)),
                ('mileage', models.PositiveIntegerField(null=True)),
                ('fuel_type', models.CharField(choices=[('Gasoline', 'GASOLINE'), ('Diesel', 'DIESEL'), ('Electric', 'ELECTRIC'), ('Hybrid', 'HYBRID')], max_length=12, null=True)),
                ('transmission', models.CharField(choices=[(cronapp.models.TransmissionType['AUTOMATIC'], 'Automatic'), (cronapp.models.TransmissionType['MANUAL'], 'Manual')], max_length=12, null=True)),
                ('color', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('speed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fuel_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('engine_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cronapp.car')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cronapp.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cronapp.user')),
            ],
        ),
    ]
