# Generated by Django 4.2.3 on 2023-07-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telemetry',
            old_name='car_id',
            new_name='car',
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
